### PR TITLE
Make some fixes 

### PR DESCRIPTION
**Pull request by Nejcc**

### CODE REVIEW

**Review by eporsche — COMMENTED** [review]
I would rather keep the lock files in the repository

**Review by eporsche — COMMENTED** [review]
The .env example is setup so it will work nicely together with sail for local development. No need to change that.

**Review by eporsche — COMMENTED** [review]
No need to decouple the seeder for user creation - there is only one at the moment.

**Review by eporsche — COMMENTED** [review]
Debugbar can be added in your local dev environment.

**Comment by Nejcc** [comment]
Debugbar  is already on dev.

**Review by eporsche — COMMENTED** [review]
Using the helper method instead of Cabon's static method - is not sth. I would prefer.

**Comment by eporsche** [comment]
Closing this pull request because of various differing opinions about the proposed changes.

**Pull request closed without merging**
